apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-coach-ui
spec:
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 180
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
