apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- digest: sha256:65d3b11a0ee1ff907e46ba911c5a7ba801953b904b2e5d38f50485d045e60392
  name: mcp-server
  newName: us-central1-docker.pkg.dev/gke-hackathon-469600/bank-of-anthos-repo/mcp-server
patches:
- path: patch-prod.yaml
