apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: mcp-server
    newName: ${REG}/mcp-server
    newTag: ${TAG:-prod}
patches:
  - path: patch-prod.yaml