apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  labels:
    app: mcp-server
    application: personal-financial-advisor
    tier: ai
spec:
  selector:
    matchLabels:
      app: mcp-server
      application: personal-financial-advisor
      tier: ai
  template:
    metadata:
      labels:
        app: mcp-server
        application: personal-financial-advisor
        tier: ai
    spec:
      containers:
      - name: mcp-server
        image: mcp-server:dev # <-- overlaid per env
        ports:
        - containerPort: 8080
