apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  labels:
    app: mcp-server
    application: bank-of-anthos
    tier: backend
    team: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
        application: bank-of-anthos
    spec:
      serviceAccountName: mcp-server
      containers:
        - name: mcp-server
          image: mcp-server:latest # overridden by overlays
          ports:
            - containerPort: 8080
          env:
            - name: MANAGEMENT_METRICS_EXPORT_STACKDRIVER_ENABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  labels:
    app: mcp-server
spec:
  selector:
    app: mcp-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-server