# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: frontend-mcs
spec:
  template:
    spec:
      selector:
        app: frontend
      ports:
      - name: https
        protocol: TCP
        port: 8080
        targetPort: 8080
---
apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: frontend-global-ingress
  annotations:
    networking.gke.io/static-ip: 34.102.238.83
spec:
  tls:
    secretName: frontend-tls-multi
  template:
    spec:
      backend:
        serviceName: frontend-mcs
        servicePort: 8080