apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
data:
  GOOGLE_CLOUD_PROJECT: "gke-hackathon-469600"
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: /tmp/.ssh/publickey
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-api-config
data:
  TRANSACTION_HISTORY_URI: "http://transactionhistory:8080"
  USER_SERVICE_URI: "http://userservice:8080"
  BALANCE_READER_URI: "http://balancereader:8080"
  LEDGER_WRITER_URI: "http://ledgerwriter:8080"
  CONTACTS_URI: "http://contacts:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-data-config
data:
  USE_DEMO_DATA: "True"
  DEMO_LOGIN_USERNAME: "user"
  DEMO_LOGIN_PASSWORD: "password"