apiVersion: v1
kind: Service
metadata:
  name: insight-agent
  labels:
    app: insight-agent
    application: bank-of-anthos
    tier: backend
    team: platform
spec:
  type: ClusterIP
  selector:
    app: insight-agent
    application: bank-of-anthos
    tier: backend
    team: platform
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insight-agent
  labels:
    app: insight-agent
    application: bank-of-anthos
    tier: backend
    team: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insight-agent
      application: bank-of-anthos
      tier: backend
      team: platform
  template:
    metadata:
      labels:
        app: insight-agent
        application: bank-of-anthos
        tier: backend
        team: platform
    spec:
      serviceAccountName: bank-of-anthos
      containers:
        - name: insight-agent
          image: us-central1-docker.pkg.dev/PROJECT/REPO/insight-agent:gemini
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-api-key
                  key: api-key
            - name: MANAGEMENT_METRICS_EXPORT_STACKDRIVER_ENABLED
              value: "false"
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
