apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: development
    team: loadgenerator
    tier: test
  name: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
      environment: development
      team: loadgenerator
      tier: test
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: loadgenerator
        environment: development
        team: loadgenerator
        tier: test
    spec:
      containers:
        - env:
            - name: FRONTEND_ADDR
              value: frontend:80
            - name: USERS
              value: "5"
            - name: LOG_LEVEL
              value: error
          image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/loadgenerator:v0.6.0@sha256:29b38aad1df4f7ad3293d6630b8c4bda102187b2cd3e2eff07a96b18732d2045
          name: loadgenerator
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
