apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: insight-agent-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: insight-agent
  minReplicas: 1  # ← change from 0 → 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
