apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
spec:
  template:
    spec:
      containers:
        - name: mcp-server
          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 30
            periodSeconds: 3
            timeoutSeconds: 2
          readinessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 2