apiVersion: apps/v1
kind: Deployment
metadata:
  name: insight-agent
spec:
  template:
    spec:
      containers:
        - name: insight-agent
          env:
            # --- Runtime mode: Vertex ---
            - name: INSIGHT_BACKEND
              value: vertex

            # --- Vertex model/location ---
            - name: VERTEX_LOCATION
              value: global
            - name: VERTEX_MODEL
              value: gemini-2.5-pro

            # Optional: project (via ConfigMap)
            - name: GOOGLE_CLOUD_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: GOOGLE_CLOUD_PROJECT

            # --- App/infra knobs ---
            - name: ENABLE_TRACING
              value: "false"
            - name: LOG_LEVEL
              value: INFO   # lower/upper both work; code uppercases

            # Downstream service URIs (cluster DNS)
            - name: USERSERVICE_URI
              value: http://userservice:8080
            - name: MCP_SERVER_URI
              value: http://mcp-server:8080

            # --- Gemini generation config (DSQ-friendly) ---
            - name: GENAI_CONCURRENCY
              value: "2"
            - name: GENAI_RPM
              value: "18"
            - name: GENAI_MAX_TOKENS
              value: "2048"
            - name: GENAI_THINK_TOKENS
              value: "1024"

          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
