apiVersion: apps/v1
kind: Deployment
metadata:
  name: insight-agent
spec:
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    spec:
      serviceAccountName: bank-of-anthos
