apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: agent-gateway
    newName: ${REG}/agent-gateway
    newTag: ${TAG:-prod}
patches:
  - path: patch-prod.yaml
configMapGenerator:
  - name: vertex-config
    literals:
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-changeme}
      - VERTEX_LOCATION=${VERTEX_LOCATION:-us-central1}
      - VERTEX_AGENT_ID=${VERTEX_AGENT_ID:-agent-123}
generatorOptions:
  disableNameSuffixHash: true