apiVersion: v1
kind: Service
metadata:
  name: budget-coach-ui-lb
  labels:
    app: budget-coach-ui
spec:
  type: LoadBalancer
  selector:
    app: budget-coach-ui
  ports:
    - name: http
      port: 80
      targetPort: 8501
