apiVersion: v1
kind: Service
metadata:
  name: insight-agent
  labels:
    app: insight-agent
    application: personal-financial-advisor
    tier: ai
spec:
  selector:
    app: insight-agent
    application: personal-financial-advisor
    tier: ai
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
