apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerwriter
spec:
  template:
    spec:
      containers:
        - name: ledgerwriter
          env:
            - name: ENABLE_TRACING
              value: "false"
            - name: ENABLE_METRICS
              value: "false"
            - name: JAVA_TOOL_OPTIONS
              value: "-Djava.io.tmpdir=/tmp -Dserver.tomcat.basedir=/tmp"
