apiVersion: apps/v1
kind: Deployment
metadata:
  name: insight-agent
spec:
  template:
    spec:
      containers:
        - name: insight-agent
          env:
            - name: ENABLE_TRACING
              value: "true"
            - name: LOG_LEVEL
              value: info
