# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Code Tests"
on:
  push:
    # run on pushes to master or release/*
    branches:
      - master
      - release/*
  pull_request:
    # run on pull requests targeting master
    branches:
      - master
jobs:
  run-tests:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: License Check
      run: |
        set -x
        git init
        git add --all
        git -c user.name="CI Bot" -c user.email="<>" commit -m "initial state"
        addlicense ./
        if [[ -n $(git status -s) ]]; then
          exit 1
        fi
    - name: Java Checkstyle
      timeout-minutes: 20
      run: |
        mvn checkstyle:check
    - name: Python Checkstyle
      timeout-minutes: 20
      run: |
        pylint --disable=F0401 --disable=W0511 --disable=E1101 --disable=R0801 --disable=R0903 --disable=R0915 ./src/*/*.py
        # disabled warnings: import loading, todos, function members, duplicate code, public methods, too many statements
    - name: Java Unit Tests
      timeout-minutes: 20
      run: |
        mvn test
    - name: Python Unit Tests
      timeout-minutes: 20
      run: |
        set -x
        cd src/userservice
        python3 -m venv env
        source env/bin/activate
        pip install -r tests/requirements-test.txt
        python -m pytest -v -p no:warnings
        deactivate
